config-version: 2

name: 'intercom_metrics'
version: '0.1.0'

require-dbt-version: [">=1.0.0", "<2.0.0"]

models:
  intercom_metrics:
    metrics:
      +enabled: true
      +materialized: table


#assigning variables to staged models from fivetran 
vars: 
  #enter the schema where your intercom source data is kept. This is the raw data that you sync from fivetran
  #intercom_source: 
    #intercom_schema: fivetran_intercom
  intercom_metrics:
    admin: "{{ ref('stg_intercom__admin') }}"
    company_history: "{{ ref('stg_intercom_company_history') }}"
    contact_company_history: "{{ ref('stg_intercom__contact_company_history') }}"
    contact_history: "{{ ref('stg_intercom__contact_history') }}"
    conversation_contact_history: "{{ ref('stg_intercom__conversation_contact_history') }}"
    conversation_history: "{{ ref('stg_intercom__conversation_history') }}"
    conversation_part_history: "{{ ref('stg_intercom__conversation_part_history') }}"
    conversation_tag_history: "{{ ref('stg_intercom__conversation_tag_history') }}"
    team: "{{ ref('stg_intercom__team') }}"

  good_rating_threshold: 5
