config-version: 2

name: 'intercom_metrics'
version: '0.1.0'

profile: 'snowflake-dev-dbt'

require-dbt-version: [">=1.0.0", "<2.0.0"]

models:
  intercom_metrics:
    +materialized: table

#assigning variables to staged models from fivetran 
vars: 
  intercom_metrics:
    admin: "{{ ref('stg_intercom__admin') }}"
    company_history: "{{ ref('stg_intercom_company_history') }}"
    contact_company_history: "{{ ref('stg_intercom__contact_company_history') }}"
    contact_history: "{{ ref('stg_intercom__contact_history') }}"
    conversation_contact_history: "{{ ref('stg_intercom__conversation_contact_history') }}"
    conversation_history: "{{ ref('stg_intercom__conversation_history') }}"
    conversation_part_history: "{{ ref('stg_intercom__conversation_part_history') }}"
    conversation_tag_history: "{{ ref('stg_intercom__conversation_tag_history') }}"
    team: "{{ ref('stg_intercom__team') }}"

    
  intercom_source: #using to overrite source dependancy 
    intercom_schema: fivetran_intercom
